
module.exports = {
  home: require('./home')
  , error: require('./error')
  , search: require('./search')
  , users: require('./users')
  , roles: require('./roles')
  , pregnancy: require('./pregnancy')
  , referral: require('./referral')
  , labs: require('./labs')
  , pregnancyHistory: require('./pregnancyHistory')
  , prenatalExam: require('./prenatalExam')
  , vaccination: require('./vaccination')
  , medication: require('./medication')
  , checkInOut: require('./checkInOut')
  , report: require('./report')
  , dewormingRpt: require('./dewormingRpt')
  , priorityList: require('./priorityList')
  , summaryRpt: require('./summaryRpt')
  , dohMasterListRpt: require('./dohMasterListRpt')
  , teaching: require('./teaching')
};
